server:
    port: 8080
    tomcat:
        threads:
            max: 500
            min-spare: 50
        max-connections: 10000
        accept-count: 65535
        connection-timeout: 30000
        max-http-form-post-size: 2MB
        max-swallow-size: 2MB
        compression:
            enabled: true
            min-response-size: 1024
            mime-types: application/json,application/xml,text/html,text/plain

spring:
    application:
        name: high-performance-api
    threads:
        virtual:
            enabled: true

# Configuración de métricas y monitoreo
management:
    endpoints:
        web:
            exposure:
                include: health,info,metrics
    endpoint:
        health:
            show-details: always
    metrics:
        export:
            prometheus:
                enabled: true