management:
    endpoint:
        health:
            show-details: never
    endpoints:
        web:
            exposure:
                include: health,metrics
server:
    port: 8080
    servlet:
        context-path: /
spring:
    application:
        name: high-performance-api
    threads:
        virtual:
            enabled: true
